@"
[project]
name = "yolo-aimbot"
version = "0.0.0"
description = "Temp stub for CI"
authors = [{name = "temp"}]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
"@