name: ci # Status Check 名稱

on:
  pull_request:
  push:
    branches: [main] # main 直推也跑

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 直接把 repo 放到工作目錄根
      - uses: actions/checkout@v3
        with:
          path: . # ★ 關鍵：避免 nested 資料夾

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 2️⃣ （可選）除錯查看目錄結構
      - name: Debug list files
        run: |
          pwd
          ls -lah

      # 3️⃣ 安裝依賴
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .                # editable install
          pip install pytest              # pytest 當前用得到的套件

      # 4️⃣ 執行測試
      - name: Run pytest
        run: pytest -q
