name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pydantic pytest

      - name: Run pytest (allow no tests)
        shell: bash
        run: |
          pytest -q || RC=$?
          if [ "${RC:-0}" = "5" ]; then
            echo "::warning ::No tests collected – treating as success"
            exit 0
          else
            exit ${RC:-0}
          fi
