name: ci # 這個名稱會出現在 Status Check 清單

on:
  pull_request:
  push:
    branches: [main] # main 直推也跑

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ➤ Check out 專案（預設即放在 $GITHUB_WORKSPACE 根目錄）
      - uses: actions/checkout@v3

      # ➤ Python 3.11
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # （可選）列出工作目錄，方便除錯
      - name: Debug list files
        run: |
          pwd
          ls -lah

      # ➤ 安裝最小依賴（FastAPI / Pydantic / pytest）
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pydantic pytest

      # ➤ 執行 pytest
      - name: Run pytest
        run: pytest -q
