name: ci # 這個名字將出現在 Status Check 清單

on:
  pull_request:
  push:
    branches: [main] # main 直推也要跑

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          # 如用 poetry: pip install poetry && poetry install --no-root

      - name: Run pytest
        run: pytest -q
