name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pydantic pytest

      # --- 關鍵區塊：處理 exit code 5 ------------------
      - name: Run pytest
        shell: bash
        run: |
          set -e
          pytest -q || EXIT=$?
          if [ "${EXIT:-0}" = "5" ]; then
            echo "No tests collected – treating as success"
            exit 0
          else
            exit ${EXIT:-0}
          fi
      # ------------------------------------------------
